### ISSUE TITLE
Kaleido executable not found (on Windows 10)

### ISSUE THREAD

**Issue by MSeifert04** [plotly/Kaleido#61] opened 2020-12-07 22:45 UTC
I just installed kaleido 0.1.0 and plotly (python 3.9, newest pip inside a virtualenv on Windows 10) and the first attempt failed:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2f> in <module>
     24 
     25 fig.show()
---> 26 fig.write_image(r"fig1.png")

...venv3.9\lib\site-packages\plotly\basedatatypes.py in write_image(self, *args, **kwargs)
   3804         import plotly.io as pio
   3805 
-> 3806         return pio.write_image(self, *args, **kwargs)
   3807 
   3808     # Static helpers

...venv3.9\lib\site-packages\plotly\io\_kaleido.py in write_image(fig, file, format, scale, width, height, validate, engine)
    243     # -------------
    244     # Do this first so we don't create a file if image conversion fails
--> 245     img_data = to_image(
    246         fig,
    247         format=format,

...venv3.9\lib\site-packages\plotly\io\_kaleido.py in to_image(fig, format, width, height, scale, validate, engine)
    129     # ---------------
    130     fig_dict = validate_coerce_fig_to_dict(fig, validate)
--> 131     img_bytes = scope.transform(
    132         fig_dict, format=format, width=width, height=height, scale=scale
    133     )

...venv3.9\lib\site-packages\kaleido\scopes\plotly.py in transform(self, figure, format, width, height, scale)
    101         # Transform in using _perform_transform rather than superclass so we can access the full
    102         # response dict, including error codes.
--> 103         response = self._perform_transform(
    104             figure, format=format, width=width, height=height, scale=scale
    105         )

...venv3.9\lib\site-packages\kaleido\scopes\base.py in _perform_transform(self, data, **kwargs)
    278         """
    279         # Ensure that kaleido subprocess is running
--> 280         self._ensure_kaleido()
    281 
    282         # Perform export

....venv3.9\lib\site-packages\kaleido\scopes\base.py in _ensure_kaleido(self)
    164                     # spaces.  The subprocess.Popen docs makes it sound like this shouldn't be
    165                     # necessary.
--> 166                     proc_args = self._build_proc_args()
    167                     self._proc = subprocess.Popen(
    168                         proc_args,

....venv3.9\lib\site-packages\kaleido\scopes\base.py in _build_proc_args(self)
    111         :return: list of flags
    112         """
--> 113         proc_args = [self.executable_path(), self.scope_name]
    114         for k in self._scope_flags:
    115             v = getattr(self, k)

...venv3.9\lib\site-packages\kaleido\scopes\base.py in executable_path(cls)
     87                 path = os.environ.get("PATH", os.defpath)
     88                 formatted_path = path.replace(os.pathsep, "\n    ")
---> 89                 raise ValueError(
     90                     """
     91 The kaleido executable is required by the kaleido Python library, but it was not included

ValueError: 
The kaleido executable is required by the kaleido Python library, but it was not included
in the Python package and it could not be found on the system PATH.

Searched for included kaleido executable at:
    ...venv3.9\lib\site-packages\kaleido\executable\kaleido
```

The interesting bit is that the executable is almost there (IPython debugger):

```
ipdb>  vendored_executable_path
'...venv3.9\\lib\\site-packages\\kaleido\\executable\\kaleido'
ipdb>  os.path.exists(vendored_executable_path)
False
ipdb>  os.path.exists('...venv3.9\\lib\\site-packages\\kaleido\\executable\\bin')
True
ipdb>  os.path.exists('...venv3.9\\lib\\site-packages\\kaleido\\executable\\kaleido.cmd')
True
ipdb>  os.path.exists('...venv3.9\\lib\\site-packages\\kaleido\\executable\\bin\\kaleido.exe')
True
ipdb>  exit
```

```
...venv3.9\Lib\site-packages\kaleido\executable> tree . /f
...VENV3.9\LIB\SITE-PACKAGES\KALEIDO\EXECUTABLE
│   CREDITS.html
│   kaleido.cmd
│   LICENSE.txt
│   version
│
├───bin
│   │   chrome_debug.log
│   │   debug.log
│   │   icudtl.dat
│   │   kaleido.exe
│   │   settings.dat
│   │
│   ├───locales
│   ├───reports
│   └───swiftshader
│           libEGL.dll
│           libEGL.dll.lib
│           libEGL.dll.pdb
│           libGLESv2.dll
│           libGLESv2.dll.lib
│           libGLESv2.dll.pdb
│
└───js
        kaleido_scopes.js
```

I'm not sure if I did something wrong and I hope I included sufficient information so this issue is useful. Please let me know if I need to amend something.

**Comment by jonmmease** [comment] 2020-12-07 23:04
Thanks for the report @MSeifert04. Have you tried older versions of kaleido in Python 3.9?  Have you tried with an older version of Python?  

I'll do some experiments, but looks like it might have something to do with how the `.cmd` extension is treated when checking for file existence.

**Comment by jonmmease** [comment] 2020-12-07 23:21
Never mind, I can reproduce it. FWIW, this only affects pip packages on Windows in kaleido version 0.1.0.

Other operating systems, and Windows installed from conda-forge using conda are ok.

# Workaround
Here's a workaround until we get a fix out.  If you add kaleido's executable directory to your `PATH`, it will find it.

```python
import os
os.environ["PATH"] = os.environ["PATH"] + ";...venv3.9\\lib\\site-packages\\kaleido\\executable\\"
```

**Comment by MSeifert04** [comment] 2020-12-08 10:20
@jonmmease Thank you for digging into the issue. I tried both the workaround and the commit https://github.com/plotly/Kaleido/commit/e05d089995877753282c1326c473e01873448174 and, indeed, both do solve the error on my machine. 

Thank you very much! 👍

**Comment by jonmmease** [comment] 2020-12-08 10:22
Fixed in https://github.com/plotly/Kaleido/commit/e05d089995877753282c1326c473e01873448174 and released on PyPI as version `0.1.0.post1`.

Thanks again for letting us know!

Note: 0.1.0.post1 was only released only for Windows pip packages, as no other operating systems or package formats were affected.

**Closed by jonmmease** 2020-12-08 10:22 UTC
Labels: bug

**Comment by mgroth0** [comment] 2021-03-24 00:32
I'm having this problem on Mac, python 3.9

**Comment by mgroth0** [comment] 2021-03-24 00:38
I tried `os.environ["PATH"] = "/Users/matt/miniconda3/envs/dnn39/bin/"`. This actually had an effect, but only lead to a different error: 
<img width="605" alt="Screen Shot 2021-03-23 at 8 38 11 PM" src="https://user-images.githubusercontent.com/12831489/112236808-b09abf00-8c17-11eb-9e5f-4cbb8436f3fc.png">

**Comment by jonmmease** [comment] 2021-03-26 13:52
Hi @mgroth0, thanks for the info. Have you tried any older Python versions?

**Comment by jonmmease** [comment] 2021-03-26 13:53
Potentially related: https://superuser.com/questions/1496039/python-path-issue-with-dirname-command-not-found-and-conda-environment-python-n

**Comment by TheMadMoose** [comment] 2024-09-09 13:26
Had the same problem on Windows 11. I initially followed numerous comments recommending installing version 0.1.0. That solved my initial problem (hanging), but introduced the “executable not located” issue mentioned here.

I then went version by version (of Kaleido) starting from the latest and made it work without any adjustments on version 0.1.0.post1.

Sorry, if my comment is improper (please let me know! I'm not too sure what's okay to do here and what not, haha).
Figured it might help someone else in a similar boat.
