### ISSUE TITLE
Support passing arbitrary Chromium arguments to the kaleido binary

### ISSUE THREAD

**Issue by aschmied** [plotly/Kaleido#45] opened 2020-09-24 23:05 UTC
We are using Kaleido 0.0.3 in a Docker container. Kaleido crashes due to "/dev/shm" space being limited to 64 MB. To work around this, we are hacking "site-packages/kaleido/executable/kaleido" to include `--disable-dev-shm-usage` and `--single-process`.

It would be really handy if we could pass arbitrary arguments through to the Kaleido binary from our Python code.

**Comment by jonmmease** [comment] 2020-09-25 12:00
Thanks for raising this @aschmied. Yeah, I agree that would be a good idea to support customizing these options.

That said, we'd really like for kaleido to work out-of-the-box in as many configurations as possible so I'd like to think through what we can do to make this case work by default. Just to help me understand, without these options does kaleido always crash? Or does it work for small figures and crash for larger ones?

Looks like there's been quite a bit of discussion in the puppeteer project over whether to add `--disable-dev-shm-usage` by default https://github.com/puppeteer/puppeteer/issues/1834. And it looks like they did ultimately decide to do so (https://github.com/puppeteer/puppeteer/blob/17960e5d8d6b019504ef8108316b4d641db41249/src/node/Launcher.ts#L178). My understanding is that the main (only?) drawback is a potential performance regression due to the use of `/tmp/` directory files rather than shared memory for some interprocess communication.  Did you come across any other information on potential downsides of using this as a default?

What benefit did you see out of adding `--single-process`?  From a quick glance at https://www.chromium.org/developers/design-documents/process-models, it also looks like this would be a fine default for kaleido. We only ever render a single figure at a time in a singe tab, so I don't think we get any benefit from Chromium's multi-process architecture.

**Comment by aschmied** [comment] 2020-09-25 21:55
Thank you for the quick response. From the symptom, it looks like either Kaleido is leaking /dev/shm space or 64 MB of /dev/shm is not enough to run Kaleido. We generate three figures and pack them up to be downloaded together. They are the same dimensions, but one contains many more data points. Kaleido usually fails on the figure with many data points, but not always.

After a docker container restart, I can generate all three figures successfully once. The second time Kaleido fails on the third figure (the one with many data points). After doubling the /dev/shm  space from 64 MB to 128 MB, I can generate the figure about 5 times before a failure. With 1 GB of /dev/shm I can generate the figure as many times as I like. I was able to get some debugging output that included a stack trace. I can post that if you'd like. This might be expected behaviour: there is a warning log when I start Kaleido on the command line saying 64 MB of SHM is not enough.

Unfortunately, I don't know why `--single-process` is required. I tried it following [this comment](https://groups.google.com/a/chromium.org/g/headless-dev/c/qqbZVZ2IwEw/m/XMKlEMP3EQAJ) in a thread where someone is asking for help getting Chromium running in AWS Lambda. I needed both `--disable-dev-shm-usage` and `--single-process` to make it go.

There is a note in that process model doc that `--single-process` gets less testing and is intended for development, so not ideal for production, but for my case it seemed to be required.

**Comment by jonmmease** [comment] 2020-09-26 11:17
Thanks for the details @aschmied, that's helpful.

Yeah, if you could include whatever stack traces you gathered (along with a description of the flags you were using if possible) that would be great.  I'd be especially interested in what you saw when using `--disable-dev-shm-usage` without `--single-process`.

**Comment by aschmied** [comment] 2020-09-29 00:28
Here is the stack trace along with the various combinations of args and /dev/shm sizes I worked through. The args named below were the only non-default args I added. I added them by modifying this line in "site-packages/kaleido/executable/kaleido":

```
./bin/kaleido --no-sandbox --allow-file-access-from-files --disable-breakpad $@
```

**With `--disable-dev-shm-usage` and 1 GB /dev/shm**

works

**With `--single-process` and 1 GB /dev/shm**

works

**With `--disable-dev-shm-usage` and 64 MB /dev/shm**

Seems to hang rendering one of the images, but I do not get a stack trace. Everything seems idle from the top output:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0 1993608 195140  53752 S   0.0  1.0   0:03.54 our_process
   39 root      20   0   18184   2952   2700 S   0.0  0.0   0:00.00 kaleido
   44 root      20   0  307864  52792  43496 S   0.0  0.3   0:00.40 kaleido
   46 root      20   0  164184  26500  21592 S   0.0  0.1   0:00.00 kaleido
   47 root      20   0  164184  26720  21812 S   0.0  0.1   0:00.00 kaleido
   59 root      20   0  694756  45444  27312 S   0.0  0.2   0:12.77 kaleido
   60 root      20   0  240696  41716  35124 S   0.0  0.2   0:00.11 kaleido
  140 root      20   0   18188   3328   2788 S   0.0  0.0   0:00.01 bash
  206 root      20   0   41040   3228   2716 R   0.0  0.0   0:00.02 top
```

**With `--single-process` and 64 MB /dev/shm**

Out-of-memory error. This does not appear related to /dev/shm size, but enlarging /dev/shm works around it.

```
Traceback (most recent call last):
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/our_package_name/index.py", line 57, in download_report
    report = get_report(incident_id)
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/our_package_name/storage_interface/incident_reporting.py", line 10, in get_report
    incident_report = _build_incident_report(incident_id)
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/our_package_name/storage_interface/incident_reporting.py", line 18, in _build_incident_report
    return IncidentReport(incident)
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/our_package_name/data_models/incident_report.py", line 46, in __init__
    constants.MOTION_TYPE_SELECTION_RELATIVE, image_dir_name)
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/our_package_name/data_models/incident_report.py", line 129, in _build_graph_page
    height=self.GRAPH_HEIGHT_FULL_SIZE)
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/plotly/basedatatypes.py", line 3251, in write_image
    return pio.write_image(self, *args, **kwargs)
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/plotly/io/_kaleido.py", line 251, in write_image
    engine=engine,
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/plotly/io/_kaleido.py", line 131, in to_image
    fig_dict, format=format, width=width, height=height, scale=scale
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/kaleido/scopes/plotly.py", line 103, in transform
    figure, format=format, width=width, height=height, scale=scale
  File "/opt/conda/envs/our-package-name/lib/python3.7/site-packages/kaleido/scopes/base.py", line 226, in _perform_transform
    raise ValueError(message)
ValueError: Transform failed. Error stream:

[0928/233351.123743:FATAL:memory.cc(38)] Out of memory. size=7200000
#0 0x56340f68c8a9 base::debug::CollectStackTrace()
#1 0x56340f5fb203 base::debug::StackTrace::StackTrace()
#2 0x56340f60b925 logging::LogMessage::~LogMessage()
#3 0x56340f625ab9 base::internal::OnNoMemoryInternal()
#4 0x56340ff9b691 viz::bitmap_allocation::AllocateSharedBitmap()
#5 0x5634111aa008 blink::DrawingBuffer::CreateOrRecycleBitmap()
#6 0x5634111aa4ba blink::DrawingBuffer::FinishPrepareTransferableResourceSoftware()
#7 0x5634111aa2eb blink::DrawingBuffer::PrepareTransferableResourceInternal()
#8 0x5634111aa222 blink::DrawingBuffer::PrepareTransferableResource()
#9 0x5634104afbf6 cc::TextureLayer::Update()
#10 0x56340fe90a79 cc::LayerTreeHost::DoUpdateLayers()
#11 0x56340fe9076c cc::LayerTreeHost::UpdateLayers()
#12 0x56340ff05c6f cc::ProxyMain::BeginMainFrame()
#13 0x56340ff0b5bd base::internal::Invoker<>::RunOnce()
#14 0x56340f63b94b base::TaskAnnotator::RunTask()
#15 0x56340f64aa6b base::sequence_manager::internal::ThreadControllerImpl::DoWork()
#16 0x56340f63b94b base::TaskAnnotator::RunTask()
#17 0x56340f64c45e base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
#18 0x56340f64c1f0 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
#19 0x56340f61071a base::MessagePumpDefault::Run()
#20 0x56340f64c9e5 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#21 0x56340f628a0e base::RunLoop::Run()
#22 0x56340f6622b7 base::Thread::ThreadMain()
#23 0x56340f69c21e base::(anonymous namespace)::ThreadFunc()
#24 0x7f67966d34a4 start_thread
#25 0x7f6795316d0f clone
Task trace:
#0 0x56340ff0a2c2 cc::ProxyImpl::ScheduledActionSendBeginMainFrame()
#1 0x56340fc543b5 mojo::Connector::ReadAllAvailableMessages()
#2 0x56340fc6c426 mojo::SimpleWatcher::Context::Notify()
#3 0x56340fc6c426 mojo::SimpleWatcher::Context::Notify()
#4 0x56340ff068c3 cc::ProxyMain::SendCommitRequestToImplThreadIfNeeded()
Task trace buffer limit hit, update PendingTask::kTaskBacktraceLength to increase.
IPC message handler context: 0xB99CF134

Received signal 6
#0 0x56340f68c8a9 base::debug::CollectStackTrace()
#1 0x56340f5fb203 base::debug::StackTrace::StackTrace()
#2 0x56340f68c445 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f67966dd0e0 (/lib/x86_64-linux-gnu/libpthread-2.24.so+0x110df)
#4 0x7f6795260fff gsignal
#5 0x7f679526242a abort
#6 0x56340f68b3a5 base::debug::BreakDebugger()
#7 0x56340f60bdc2 logging::LogMessage::~LogMessage()
#8 0x56340f625ab9 base::internal::OnNoMemoryInternal()
#9 0x56340ff9b691 viz::bitmap_allocation::AllocateSharedBitmap()
#10 0x5634111aa008 blink::DrawingBuffer::CreateOrRecycleBitmap()
#11 0x5634111aa4ba blink::DrawingBuffer::FinishPrepareTransferableResourceSoftware()
#12 0x5634111aa2eb blink::DrawingBuffer::PrepareTransferableResourceInternal()
#13 0x5634111aa222 blink::DrawingBuffer::PrepareTransferableResource()
#14 0x5634104afbf6 cc::TextureLayer::Update()
#15 0x56340fe90a79 cc::LayerTreeHost::DoUpdateLayers()
#16 0x56340fe9076c cc::LayerTreeHost::UpdateLayers()
#17 0x56340ff05c6f cc::ProxyMain::BeginMainFrame()
#18 0x56340ff0b5bd base::internal::Invoker<>::RunOnce()
#19 0x56340f63b94b base::TaskAnnotator::RunTask()
#20 0x56340f64aa6b base::sequence_manager::internal::ThreadControllerImpl::DoWork()
#21 0x56340f63b94b base::TaskAnnotator::RunTask()
#22 0x56340f64c45e base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
#23 0x56340f64c1f0 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
#24 0x56340f61071a base::MessagePumpDefault::Run()
#25 0x56340f64c9e5 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#26 0x56340f628a0e base::RunLoop::Run()
#27 0x56340f6622b7 base::Thread::ThreadMain()
#28 0x56340f69c21e base::(anonymous namespace)::ThreadFunc()
#29 0x7f67966d34a4 start_thread
#30 0x7f6795316d0f clone
  r8: 0000000000000000  r9: 00007f678d248cd0 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007f678d249f88 r13: 00007f678d248f60 r14: 00007f678d249f90 r15: aaaaaaaaaaaaaaaa
  di: 0000000000000002  si: 00007f678d248cd0  bp: 00007f678d248f10  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f6795260fff  sp: 00007f678d248d48
  ip: 00007f6795260fff efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Comment by aschmied** [comment] 2020-09-29 00:29
I wasn't sure how to get logs from Kaleido. I can redo the failure cases with logging enabled if you let me know how to do it.

**Comment by jonmmease** [comment] 2020-09-29 09:20
Thanks a lot for the extra info @aschmied.

> I wasn't sure how to get logs from Kaleido. I can redo the failure cases with logging enabled if you let me know how to do it.

When kaleido hangs you should be able to get some logs by interrupting the execution of the interpreter (Ctrl+C in python or ipython repls, or the "Stop Kernel" button in Jupyter notebook).  Then executing this:

```python
print(scope._std_error.getvalue().decode())
```
(cross reference: I opened https://github.com/plotly/Kaleido/issues/48 to remind us to make this easier)

It's possible that this hanging behavior is the same thing happening in https://github.com/plotly/Kaleido/issues/42, where kaleido would hang after exporting a few images.  This was due to a memory leak that should be fixed on master by https://github.com/plotly/Kaleido/pull/43.

So if you can, it would be also be helpful if you could repeat these tests with the alpha build at https://github.com/plotly/Kaleido/releases/tag/v0.1.0a2, and using the above to check for logging messages if it still hangs.  You can install the alpha build with:

```
pip install https://github.com/plotly/Kaleido/releases/download/v0.1.0a2/kaleido-0.1.0a2-py2.py3-none-manylinux1_x86_64.whl
```

Thanks for helping us work this out!

**Comment by aschmied** [comment] 2020-09-29 13:30
Trying these again with the 0.1.0.a2 release and a 64 MB /dev/shm.

**No options**

Hangs with no output like before.

**--disable-dev-shm-usage**

Hangs with no output like before.

**--single-process**

OOM stack trace like before.

This was not what I expected, so I double-checked that I have the correct version installed:

```
# pip show kaleido
Name: kaleido
Version: 0.1.0a2
...
```

Getting the logs using an interactive terminal will be cumbersome. This code is a few layers deep: in a Flask app inside a Docker container. I tried getting a stack trace using the GDB macros linked in [this SO answer](https://stackoverflow.com/a/147114), but that requires a debug build of Python. I also tried Pyrasite following [this gist](https://gist.github.com/reywood/e221c4061bbf2eccea885c9b2e4ef496). It printed something, but appeared to get into an infinite recursion in Waitress's task queue and the container got killed with nothing useful printed.

**Comment by jonmmease** [comment] 2020-09-29 13:45
Ok, thanks for trying. So just to summarize:
 1. The alpha behaves identical to the 0.0.3 version you were using
 2. In both cases, the only way to get it working without changing the `/dev/shm` size is to use both the `--disable-dev-shm-usage` and `--single-process` flags.
 3. If you raise `/dev/shm` to 1GB, either `--disable-dev-shm-usage` or `--single-process` flags gets things working by itself?

Could you verify that I have that right?

> Getting the logs using an interactive terminal will be cumbersome.

Ok, another option is to add a print/log statement in the standard error collection loop here:

https://github.com/plotly/Kaleido/blob/6c704bd65acf9b8852d7862ba154d7e032e87d5a/repos/kaleido/py/kaleido/scopes/base.py#L68-L76

Thanks!

**Comment by jonmmease** [comment] 2020-09-29 13:59
BTW, did you happen to try any of the other non-default process models from https://www.chromium.org/developers/design-documents/process-models?  `--process-per-site` and `--process-per-tab`.  These don't have the "it is designed for testing and development purposes" caveat so might be candidates for a default value if they make a difference.

**Comment by aschmied** [comment] 2020-10-09 14:23
@jonmmease sorry for the delayed reply. To answer the questions from your previous comment:

1. Correct
1. Correct
1. Not quite. With "/dev/shm" at 1 GB, I did not need to modify the `kaleido` console args at all. The defaults worked

I have not tried the other process models, but that is a good suggestion.

I see you have a PR open to address this already. Thank you for the quick turnaround!

**Closed** 2020-10-23 09:10 UTC
Labels: enhancement

**Comment by jonmmease** [comment] 2021-02-25 16:44
@aschmied, something similar came up again in https://github.com/plotly/Kaleido/issues/74 for a user running on Lambda.  Were you running on Lambda?  I'm wondering if there's something we can do to detect when to default to adding the `--single-process` flag, so I was curios what environment you using when you ran into this.

Thanks!

**Comment by jonmmease** [comment] 2021-02-25 16:45
I would also be interested to know if you happened to have had the chance to try the  `--process-per-site` and `--process-per-tab` flags.
